#!/usr/bin/ruby
require 'optparse'
require 'pathname'
require 'logger'
require 'open3'
require 'fileutils'
require 'thread'
require './lib/log'
require './lib/pipeline'

options = Options.new

Thread.abort_on_exception = true

Log.set_out(options.log_file)
Log.info options.summary

pipeline = Pipeline.new(options, Log)

Log.info "Ripchord shutting down"



